# Generated by Django 3.0 on 2021-04-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Child', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Email_ID', models.EmailField(max_length=30)),
                ('Dob', models.DateField()),
                ('Mobile_Number', models.IntegerField()),
                ('PAN', models.IntegerField()),
                ('Address', models.TextField()),
                ('Country', models.CharField(max_length=20)),
                ('Postal_code', models.IntegerField()),
                ('City', models.CharField(max_length=20)),
            ],
        ),
    ]
